apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 8080  # The port used to access ArgoCD
      targetPort: 8080  # The port where ArgoCD is running within the pod
      nodePort: 30080  # The port exposed on the host (adjust as needed)
  selector:
    app.kubernetes.io/name: argocd-server
