apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd  
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.crossplane.io/stable'
    # targetRevision: 1.13.2
    targetRevision: 1.15.0
    chart: crossplane
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true